### ISSUE TITLE
Update NAICS tables

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/oasis-plus#371]
Currently, when reviewing the [NAICS by domains](https://www.gsa.gov/oasis-plus/about/domains-labor-categories/naics-codes/), the NAICS codes themselves are not easily scannable, perhaps we would want to remove the first column (which is just shorthand for the domain) and instead have the NAICS codes listed there. 

- Delete column 1, `Domain`
- Column 1 becomes `NAICS code`
- Column 2 becomes `NAICS title`

**Comment by vickimcfadden** [comment]
@klohman when you're back, interested in your thoughts here. This would be for mid-May / sprint 5.

**Comment by klohman** [comment]
> @klohman when you're back, interested in your thoughts here. This would be for mid-May / sprint 5.

@vickimcfadden @rosamundtgov Agree,  we could remove the first column since it is redundant. A larger thought is could we combine this table with the similar table that currently exists in the ordering guide ([here](https://www.gsa.gov/oasis-plus/ordering-guide/#appendix-a-performance-areas---domains) so we have one source of truth for the NAICS code info by domain?

**Comment by rosamundtgov** [comment]
@klohman I can't see a reason not to combine them. Could we also separate NAICS code into its own column, so users can sort or filter? I don't see a reason for it to be combined with the title.

**Comment by klohman** [comment]
@rosamundtgov Added a note to the [OASIS+ Ordering Guide Crosswalk ](https://docs.google.com/spreadsheets/d/1w295g0iQUGkXADDF0nTolOwFMYs3yAWwbS2__Wxntck/edit#gid=757551931). let's propose this when we walk through the ordering guide mapping with PSHC.

**Comment by rosamundtgov** [comment]
Replaced by issue 445 - archiving.
